language: python
python:
  - 3.6
addons:
  chrome: stable
before_install:
  - python --version
  - pip install -U pip
  - pip install --upgrade pip
  - pip install -r requirements.txt
#install:
#  - pip install ".[test]" . # install package + test dependencies
script: pytest openCart/tests/test_by_main.py # run tests
